version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: gerador_orcamentos_backend_dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CORS_ORIGINS=http://localhost:3001
    volumes:
      - ./backend:/app
      - /app/instance
    networks:
      - app-network
    command: python app.py
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: gerador_orcamentos_frontend_dev
    ports:
      - "3001:3001"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev -- --host 0.0.0.0 --port 3001
    restart: unless-stopped
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge